fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort . --profile black --filter-files
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black .
        pass_filenames: false
        language: system
