[tool.poetry]
name = "Z3R0"
version = "3.3.0"
description = "A multi-purpose open source discord bot"
authors = ["null2264"]
license = "MPL-2.0"

[tool.poetry.dependencies]
aiohttp = "3.7.3"
python = "^3.8"
beautifulsoup4 = "^4.9.3"
"discord.py" = {git = "https://github.com/ZiRO-Bot/enhanced-discord.py", rev = "2367d9d7e2d9fec871e34c5b0f3b88f717060974"}
discord-ext-menus = "^1.1"
fuzzywuzzy = "0.18.0"
humanize = "3.7.0"
jishaku = "^2.2.0"
Pillow = "^8.3.1"
"prettify.py" = {git = "https://github.com/ShineyDev/prettify.py", branch = "main"}
python-dateutil = "^2.8.2"
python-Levenshtein = "^0.12.2"
pytz = "^2021.1"
pyparsing = "^2.4.7"
requests = "^2.26.0"
tagscriptengine = {git = "https://github.com/ZiRO-Bot/TagScript", rev = "4b89a369bb6e36ec07da75834da67dee0e351051"}
uvloop = "^0.15.3"
typing-extensions = "^3.10.0"
databases = "^0.4.3"
asyncpg = {version = "^0.23.0", optional = true}
aiomysql = {version = "^0.0.21", optional = true}
aiosqlite = {version = "^0.17.0", optional = true}
aiopg = {version = "^1.3.1", optional = true}
PyNaCl = {version = ">=1.3.0,<1.5", optional = true}
SQLAlchemy = "<1.4"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
isort = "^5.9.3"
pre-commit = "^2.13.0"
pyproject-flake8 = "^0.0.1-alpha.2"

[tool.poetry.extras]
postgresql = ["asyncpg"]
mysql = ["aiomysql"]
sqlite = ["aiosqlite"]
"postgresql+aiopg" = ["aiopg"]
voice = ["PyNaCl"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max-line-length = 88
select = "C,E,F,W,B,B950"
extend-ignore = "E203,E501"

[tool.isort]
profile = "black"
multi_line_output = 3
lines_after_imports = 2
