version: "3"

services:
  bot:
    container_name: zibot
    image: ghcr.io/ziro-bot/z3r0:latest
    restart: always
    environment:
      ZIBOT_TOKEN: 'YOUR_TOKEN'
      ZIBOT_DB_URL: 'postgres://postgres:pass@db:5432/zibot'
    depends_on:
      - db
  
  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
      POSTGRES_DB: zibot
