version: "3"

services:
  bot:
    container_name: zibot
    image: ghcr.io/ziro-bot/z3r0:latest
    volumes:
      - "./data:/app/data"
      - "./migrations:/app/migrations"
      - "./config.py:/app/config.py"
