"""
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
"""

from tortoise import fields
from tortoise.models import Model


""" - WARNING: BREAKING CHANGES -----
- Due to how tortoise works, relation fields will have automatically use
  snake_case, for e.g.:

    guild.id -> commandsLookup.guild_id

- Rename commands_lookup -> commandsLookup to be more consistent

- Datetime columns now uses DatetimeField, which translated to:
  MySQL = DateTime, PostgreSQL = DateTime, SQLite = NUMERIC (timestamp)

  And will actually returns datetime.datetime instead of timestamp (no need to
  do datetime.fromtimestamp) when fetched.

  NOTE: Old datetime (which saved as timestamp) will need to be converted to
  new format in order to get the correct timezone, unless your server's time is
  set to UTC

----- Less breaking changes -----
- Every table now have id column, tortoise require every table to have
  atleast 1 primary key

- Timer's JSON column now uses JSONField from Tortoise,
  which translated to: MySQL = JSON, PostgreSQL = JsonB, SQLite = TEXT
"""


class NewBigIntField(fields.BigIntField):
    class _db_postgres:
        GENERATED_SQL = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL"


class NewIntField(fields.IntField):
    class _db_postgres:
        GENERATED_SQL = "INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL"


class Guilds(Model):
    id = fields.BigIntField(pk=True, generated=False)


class ContainsGuildId:
    # guild_id
    guild = fields.ForeignKeyField("models.Guilds", to_field="id")


class Timer(Model):
    id = NewBigIntField(pk=True)
    event = fields.TextField()
    extra = fields.JSONField()  # {"args": ..., "kwargs": ...}
    expires = fields.DatetimeField()
    created = fields.DatetimeField()
    owner = fields.BigIntField(pk=False, generated=False)


class Commands(Model):
    id = NewBigIntField(pk=True)
    type = fields.TextField()
    name = fields.TextField()
    category = fields.TextField(default="unsorted")
    description = fields.TextField(null=True)
    content = fields.TextField()
    url = fields.TextField(null=True)
    uses = fields.BigIntField(pk=False, generated=False, default=0)
    ownerId = fields.BigIntField(pk=False, generated=False)
    createdAt = fields.DatetimeField()
    visibility = fields.BooleanField(default=False)  # public or private
    enabled = fields.BooleanField(default=True)


class CommandsLookup(ContainsGuildId, Model):
    id = NewIntField(pk=True)
    # cmd_id
    cmd = fields.ForeignKeyField("models.Commands", related_name="cmd", to_field="id")
    name = fields.TextField()  # alias name

    class Meta:
        table = "commandsLookup"


class Disabled(ContainsGuildId, Model):
    id = NewIntField(pk=True)
    command = fields.TextField()


class Prefixes(ContainsGuildId, Model):
    id = NewIntField(pk=True)
    prefix = fields.TextField()

    class Meta:
        unique_together = (("prefix", "guild_id"),)


class GuildConfigs(ContainsGuildId, Model):
    id = NewIntField(pk=True)
    ccMode = fields.IntField(pk=False, generated=False, default=0)
    tagMode = fields.IntField(pk=False, generated=False, default=0)  # currently unused
    welcomeMsg = fields.TextField(null=True)
    farewellMsg = fields.TextField(null=True)
    locale = fields.TextField(null=True)

    class Meta:
        table = "guildConfigs"


class GuildChannels(ContainsGuildId, Model):
    id = NewIntField(pk=True)
    welcomeCh = fields.BigIntField(pk=False, generated=False, null=True)
    farewellCh = fields.BigIntField(pk=False, generated=False, null=True)
    modlogCh = fields.BigIntField(pk=False, generated=False, null=True)
    purgatoryCh = fields.BigIntField(pk=False, generated=False, null=True)
    announcementCh = fields.BigIntField(pk=False, generated=False, null=True)

    class Meta:
        table = "guildChannels"


class GuildRoles(ContainsGuildId, Model):
    id = NewIntField(pk=True)
    modRole = fields.BigIntField(pk=False, generated=False, null=True)
    mutedRole = fields.BigIntField(pk=False, generated=False, null=True)
    autoRole = fields.BigIntField(pk=False, generated=False, null=True)

    class Meta:
        table = "guildRoles"


class GuildMutes(ContainsGuildId, Model):
    id = NewIntField(pk=True)
    mutedId = fields.BigIntField(pk=False, generated=False)

    class Meta:
        table = "guildMutes"


class CaseLog(ContainsGuildId, Model):
    id = NewIntField(pk=True)
    caseId = fields.BigIntField(pk=False, generated=False)
    type = fields.TextField()
    modId = fields.BigIntField(pk=False, generated=False)
    targetId = fields.BigIntField(pk=False, generated=False)
    reason = fields.TextField()
    createdAt = fields.DatetimeField()

    class Meta:
        table = "caseLog"


class Users(Model):
    id = fields.BigIntField(pk=True, generated=False)
    locale = fields.TextField(null=True)
    timeZone = fields.TextField(null=True)


class Highlight(ContainsGuildId, Model):
    text = fields.TextField()
    ownerId = fields.BigIntField(pk=False, generated=False)

    class Meta:
        table = "highlight"
        unique_together = (("text", "ownerId"),)
