name: Nightly Build

on:
  push:
    branches:
      - dev
      - overhaul
    tags:
      - 3.*

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'ziro-bot/z3r0'
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Build and push \(Nightly\)
        uses: docker/build-push-action@v4
        if: !startsWith(github.ref, 'refs/tags/') && github.ref_name == 'dev' && github.repository == 'ziro-bot/z3r0'
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/ziro-bot/z3r0:nightly

      - name: Build and push \(Canary\)
        uses: docker/build-push-action@v4
        if: !startsWith(github.ref, 'refs/tags/') && github.ref_name == 'overhaul' && github.repository == 'ziro-bot/z3r0'
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/ziro-bot/z3r0:canary

      - name: Build and push \(Release\)
        uses: docker/build-push-action@v4
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'ziro-bot/z3r0'
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ghcr.io/ziro-bot/z3r0:latest
            ghcr.io/ziro-bot/z3r0:${{ env.VERSION_TAG }}
