name: Tests

on:
  push:
    paths-ignore:
      - '.github/workflows/docs.yml'
    branches:
      - overhaul
      - dev
      - "feat/*"
  pull_request:
    paths-ignore:
      - '.github/workflows/docs.yml'
    branches:
      - '**'

concurrency:
  group: tests-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

steps:
  - uses: actions/checkout@v3
  - name: Set up PDM
    uses: pdm-project/setup-pdm@v2
    with:
      python-version: 3.10

  - name: Install dependencies
    run: |
      pdm sync -G dev test

  - name: Run Tests
    run: |
      pdm run -v pytest
